export enum ActionTypes {
  PRODUCT_SET = '[PRODUCT] PRODUCT_SET',
  PRODUCT_CLEAR = '[PRODUCT] PRODUCT_CLEAR',

  PRODUCTS_SET = '[PRODUCTS] PRODUCTS_SET',
  PRODUCTS_CLEAR = '[PRODUCTS] PRODUCTS_CLEAR',

  CART_ADD = '[CART] CART_ADD',
  CART_REMOVE = '[CART] CART_REMOVE',
}
